- type: job
  id: Chemist
  name: job-name-chemist
  description: job-description-chemist
  playTimeTracker: JobChemist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 18000 #5 hrs # Corvax-RoleTime
  startingGear: ChemistGear
  icon: "JobIconChemist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Chemistry
  - Maintenance
  special:
    #start-_CorvaxNext: surgery
  - !type:AddComponentSpecial
    components:
    #- type: CPRTraining
    - type: SurgerySpeedModifier
      speedModifier: 1.75
    #end-_CorvaxNext: surgery
    - type: Skills # Corvax-Next-Skills
      skills:
      - MedicalEquipment

- type: startingGear
  id: ChemistGear
  equipment:
    id: ChemistryPDA
    ears: ClothingHeadsetMedical
    belt: ChemBag
    pocket1: HandLabeler
    eyes: ClothingEyesGlassesChemical
  #storage:
    #back:
    #- Stuff
