- type: job
  id: WardenHelper
  name: job-name-wardenMini
  description: job-description-wardenMini
  playTimeTracker: JobWarden
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 90000 #25 hrs
  startingGear: WardenMiniGear
  icon: "JobIconWardenHelper"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CanChokeGrab # Corvax-Next-Grab
      - type: Skills # Corvax-Next-Skills
        skills:
        - Shooting

- type: startingGear
  id: WardenMiniGear
  equipment:
    head: ClothingHeadHatWardenHelper
    eyes: ClothingEyesGlassesSecurity
    id: WardenPDA
    ears: ClothingHeadsetSecurity
    pocket1: WeaponPistolMk58
    pocket2: BookSpaceLaw
  storage:
    back:
    - Flash
    - MagazinePistol
    - ClothingNeckSecBadgeWardenMini
