- type: entity
  id: MedicalBiofabMachineBoard
  parent: BaseMachineCircuitboard
  name: medical biofab machine board
  description: A machine printed circuit board for a medical biofab.
  components:
    - type: Sprite
      state: medical
    - type: MachineBoard
      prototype: MedicalBiofabricator
      stackRequirements:
        Manipulator: 3
