- type: entity
  parent: BaseMachineCircuitboard
  id: MachineBluespaceHarvesterCircuitboard
  name: Bluespace Harvester board
  description: A machine board for a Bluespace Harvester
  components:
  - type: Sprite
    sprite: _CorvaxNext/Bluespace/module.rsi
    state: bluespace
  - type: MachineBoard
    prototype: BluespaceHarvester
    stackRequirements:
      Glass: 15
      Steel: 15
      CableHV: 5
      ArtificialBluespaceCrystal: 4
      Capacitor: 5
      MatterBin: 15
  - type: Item
    size: Normal

- type: entity
  parent: BaseMachineCircuitboard
  id: MachineBluespaceTransitorCircuitboard
  name: bluespace T.R.A.N.S.I.T.O.R board
  description: A machine board for a bluespace T.R.A.N.S.I.T.O.R
  components:
  - type: Sprite
    sprite: Objects/Misc/module.rsi
    state: bluespacearray
  - type: MachineBoard
    prototype: BluespaceTransitor
    stackRequirements:
      Steel: 10
      CableHV: 30
      ArtificialBluespaceCrystal: 4
      Capacitor: 15
  - type: Item
    size: Normal

- type: entity
  id: AdvancedMicrowaveMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: advanced microwave machine board
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: AdvancedMicrowave
      stackRequirements:
        Capacitor: 1
        Glass: 2
        Cable: 2
        Uranium: 2
      tagRequirements:
        Igniter:
          amount: 1
          defaultPrototype: Igniter

- type: entity
  id: HydroponicsTrayAdvancedMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: advanced hydroponics tray machine board
  description: A machine printed circuit board for a advanced hydroponics tray.
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: hydroponicsTrayAdvanced
      stackRequirements:
        Glass: 5
        Cable: 4
        Plasma: 5
      tagRequirements:
        GlassBeaker:
          amount: 3
          defaultPrototype: Beaker

- type: entity
  id: AdvancedReagentGrinderMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: advanced reagent grinder machine board
  description: A machine printed circuit board for a reagent grinder.
  components:
    - type: MachineBoard
      prototype: AdvancedKitchenReagentGrinder
      stackRequirements:
        MatterBin: 2
        Manipulator: 4
        Plasma: 5
      tagRequirements:
        GlassBeaker:
          amount: 1
          defaultPrototype: Beaker
