- type: entity
  parent: BaseMachineCircuitboard
  id: MachineBluespaceHarvesterCircuitboard
  name: Bluespace Harvester board
  description: A machine board for a Bluespace Harvester
  components:
  - type: Sprite
    sprite: _CorvaxNext/Bluespace/module.rsi
    state: bluespace
  - type: MachineBoard
    prototype: BluespaceHarvester
    stackRequirements:
      Glass: 20
      Steel: 20
      CableHV: 5
      ArtificialBluespaceCrystal: 4
  - type: Item
    size: Normal

- type: entity
  parent: BaseMachineCircuitboard
  id: MachineBluespaceTransitorCircuitboard
  name: bluespace T.R.A.N.S.I.T.O.R board
  description: A machine board for a bluespace T.R.A.N.S.I.T.O.R
  components:
  - type: Sprite
    sprite: Objects/Misc/module.rsi
    state: bluespacearray
  - type: MachineBoard
    prototype: BluespaceTransitor
    stackRequirements:
      Steel: 15
      CableHV: 30
      ArtificialBluespaceCrystal: 4
  - type: Item
    size: Normal
